### PR TITLE
Some important details.  

### PR DESCRIPTION
**Pull request by lobocode**
Added a tip for setting the webhook with osticket and how to contribute to the documentation.

### CODE REVIEW

**Comment by frdmn** [comment]
Thanks for the PR @lobocode. We're currently working on improving the docs system, so please be patient until we sorted that out first - then we can review and merge your PR. :)

Sorry for the delay.

**Comment by lobocode** [comment]
@frdmn Ok. At least pay attention in this last commit I did. Is a small (but important) correction. ;)

**Comment by frdmn** [comment]
@lobocode We always pay attention to the full PR changes. No worries :)

**Comment by lobocode** [comment]
@frdmn  Thank's!

**Pull request merged**
