### PR TITLE
Updated 'Promoting' in the Docs

### PR DESCRIPTION
**Pull request by rosehosting**
We added our blog post.

### CODE REVIEW

**Comment by Sing-Li** [comment]
**DO NOT MERGE:  NEED TO BE REVIEWED**

@rosehosting    The information in this  blog entry is outdated for many months.

It downloads and builds with Meteor in the process of deployment - a completely unsupported way to deploy Rocket.Chat.

It has been a MAJOR source of confusion for our users and created a constant stream of support cases that we have to deal with.

Please ask the contributor to update it, or remove it as soon as possible.

I have submitted similar comment months ago directly on the article but have received no reply.

**Comment by geekgonecrazy** [comment]
@rosehosting if you would like we can work with you to get an updated copy of your article?  We for sure appreciate when our community writes about us.  But we want to make sure we get people using the recommended installation methods.  Otherwise we have to deal with those support cases of people following that way and having issues.

Just let me know if you'd like some assistance 👍

**Comment by rosehosting** [comment]
We updated our blog post. Sorry for the inconvenience. Let us know if there's anything else.

**Comment by Sing-Li** [comment]
@rosehosting  Thank you very much for updating the blog post.

We will resume our recommendations of it, as an excellent deployment tutorial, through our support channels moving forward.   :+1:

**GOOD TO MERGE**

LGTM

**Comment by geekgonecrazy** [comment]
LGTM

**Pull request merged**
