### PR TITLE
Providing SAML documentation

### PR DESCRIPTION
**Pull request by gregharvey**
Your SAML documentation is currently empty, I've been setting this up so I thought I'd start documenting my steps to augment the docs for Rocket.Chat. :-)

### CODE REVIEW

**Review by engelgabriel — APPROVED** [review]

**Comment by engelgabriel** [comment]
@gregharvey Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.

**Comment by gregharvey** [comment]
All set! :-)

**Review by localguru — COMMENTED** [review]
What's the field "Custom Certificate" about?

**Comment by gregharvey** [comment]
@localguru I don't know! So I simply didn't write anything for that field...

**Pull request merged**
