### PR TITLE
Document a more secure CORS policy.

### PR DESCRIPTION
**Pull request by saplla**
Don't recommend users to use wildcard origins in CORS policies.

### CODE REVIEW

**Review by geekgonecrazy — APPROVED** [review]
LGTM :+1: Thanks for the contribution @saplla !  This is definitely better to recommend secure defaults

**Comment by MartinSchoeler** [comment]
@saplla could you sign the cla? Thanks!

**Comment by saplla** [comment]
Yes I will as soon as I can. I'm awaiting the green light from my organisation.

**Review by theorenck — APPROVED** [review]
Thank you @saplla, we are safer now ;).

**Review by MartinSchoeler — APPROVED** [review]

**Comment by MartinSchoeler** [comment]
Thanks for the contribution!

**Pull request merged**
