### PR TITLE
Project Idea for GSOC 2019

### PR DESCRIPTION
**Pull request by Pratyush1197**
This is a project idea for GSOC 2019 which is not in the project list idea. If anyone finds it interesting i can work on it during the upcoming GSOC period

### CODE REVIEW

**Comment by Sing-Li** [comment]
@Pratyush1197 what technology are you thinking of using to implement AR?

**Comment by Pratyush1197** [comment]
Sorry for such a late reply @Sing-Li 
I am planning to implement two features with augmented reality.
First to implement instant translation at the time of video chat. For this i will use speech translator api then the converted text will be displayed on the screen using any of the augmented reality SDK like Vuforia or wikitude. 
The other idea is to demonstrate the product during team chat. In this I will use image recognition feature of Augmented reality sdk. Then with the image it trace the description of image in database (uploaded by the user) and retrieve it. Then it will be displayed on the screen.

This is a very brief idea. Please guide me further

**Comment by Sing-Li** [comment]
@Pratyush1197  have you setup a Rocket.Chat  dev environment yet?   Do you know what video technology Rocket.Chat is using?      

You will need to prove that the technologies that you have named can actually work together.  Otherwise it is not possible to have a "project".    Very important to try and prototype it first.    Let us know.

**Comment by Sing-Li** [comment]
@Pratyush1197   we are going to close this.  If you have more information, please create a new PR or reopen this one.

**Pull request closed without merging**
