### PR TITLE
Fix more broken links

### PR DESCRIPTION
**Pull request by frdmn**
as discussed in #10

### CODE REVIEW

**Comment by Sing-Li** [comment]
LGTM

**Comment by engelgabriel** [comment]
Guys, I have to disagree. We have to keep the links working on on ANY environment, not only Redoc. The router on Redoc is misconfigured, it needs to understand the links the way they were, and not us having to adapt to it. Marcelo or George are going to fix the routes so the previews format is valid.

**Comment by engelgabriel** [comment]
Let this merged for now, and I'll revert tomorrow after the fix.

**Comment by Sing-Li** [comment]
That makes perfect sense.   I was not aware of Marcelo / George's effort, and was quite unsure of how much of the Redoc problems we want to take into our own hand - based on fixes so far.   

Glad to learn of the decision :smile:

(BTW - that gapping space on the right panel is still kind of annoying  :grin: )

**Comment by frdmn** [comment]
@engelgabriel Agree with @Sing-Li, makes totally sense. :+1: 

I didn't realize that was an option at all :)

**Pull request merged**
