### PR TITLE
Pinning messages docs updated

### PR DESCRIPTION
**Pull request by blubbi321**
With small note about the default for message pinning settings. Might confuse non-admin users otherwise as everybody is allowed to pin in Slack.

### CODE REVIEW

**Comment by frdmn** [comment]
That's a useful hint. Thanks 👍 

Waiting for another team member to confirm.

**Comment by geekgonecrazy** [comment]
LGTM 👍

**Comment by sampaiodiego** [comment]
oops, too late. :disappointed: 

so, actually the `pin-message` permission is given by default to `admin`, `owner` and `moderator` roles..

so, this sentence is not correct:

> only enabled for admin users by default

**Comment by frdmn** [comment]
@sampaiodiego Fixed in a0e2d642b16d564222e23ede3da9d40d7bb6c427:

```
Note that this is only enabled for admins, owners and moderators by default [...]  
```

**Pull request merged**
