### PR TITLE
[NEW] Create a docs to show how to use self-signed certificates on iOS & Android native apps

### PR DESCRIPTION
**Pull request by Sameesunkaria**

### CODE REVIEW

**Comment by rafaelks** [comment]
@Sameesunkaria Thank you for the PR! 👍 👏

**Review by rafaelks — APPROVED** [review]

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]
Could you add this file to the Documentation Map? https://github.com/RocketChat/docs/blob/master/contributing/documentation/documentation-map/README.md Thanks!

**Comment by Sameesunkaria** [comment]
@MartinSchoeler 👍🏻

**Review by MartinSchoeler — APPROVED** [review]
Thanks!

**Comment by Sameesunkaria** [comment]
@MartinSchoeler I believe the hyperlink on the docs isn't working because of the capitalization of `SSL` in the name of the directory.

**Comment by Sameesunkaria** [comment]
Fix posted in #701

**Pull request merged**
