### PR TITLE
Starring message and group, partially resolving Issue #389

### LINKED ISSUE #387: [NEW] Documentation for getting starred messages from a Channel/Group/DM

### LINKED ISSUE #389: [NEW] Documentation for starring a message in a Channel/Group/DM

### PR DESCRIPTION
**Pull request by Anni-Oliveira**
Starring message and group, partially resolving Issue #389, missing starring DM.
Closes #387
Closes #389

### CODE REVIEW

**Comment by graywolf336** [comment]
Hi @Anni-Oliveira, thanks for the pull request! Do you mind signing the CLA as requested in the comment right above mine?

**Comment by Anni-Oliveira** [comment]
I already did, but somehow it does not change.

**Review by MartinSchoeler — CHANGES_REQUESTED** [review]
I think it's best not to use images for now, since Rocket.Chat is going through some heavy UI redesigns and the images would quickly be outdated.

**Comment by Anni-Oliveira** [comment]
Okay, so I'll close this Pull Request and update the document.

**Pull request closed without merging**
