### PR TITLE
Add docs for Manual OpenSUSE install

### PR DESCRIPTION
**Pull request by purp**
Name says it all. =]

### CODE REVIEW

**Comment by purp** [comment]
Signed CLA, so that's done. =]

**Comment by purp** [comment]
Bumping this up for review.

**Comment by purp** [comment]
Bumping again and hoping for a quick review. =]

**Review by geekgonecrazy — APPROVED** [review]

**Comment by geekgonecrazy** [comment]
@purp thanks for the additions! Sorry for the delay here

**Pull request merged**
