### PR TITLE
Fixed typos and some grammer mistakes 

### PR DESCRIPTION
**Pull request by kerolloz**
fixed typos in /installation/manual-installation/ubuntu/snaps/README.md

### CODE REVIEW

**Comment by kerolloz** [comment]
@Sing-Li 
is the markdown linter ever gonna finish checking, I have been waiting forever :disappointed: !

**Comment by kerolloz** [comment]
would you please review @LuluGO

**Comment by shiqimei** [comment]
There are a lot of unhandled PRs before this. I think you need to be patient.

**Comment by kerolloz** [comment]
@lolimay 
okay thank you

**Review by MartinSchoeler — APPROVED** [review]
Looks good to me! Thanks for the contribution!

**Pull request merged**
