### PR TITLE
Initial layout of the csv import requirements

### PR DESCRIPTION
**Pull request by graywolf336**
I am working on a csv file importer and needed a place to layout the requirements and get them out of my head, so I decided to do it in the documents so the documentation would already be written.

### CODE REVIEW

**Comment by graywolf336** [comment]
@RocketChat/core I'd like your thoughts on the documentation for the csv importer I am starting work on. Is it easy enough for people to understand and use? Should I add something that is missing to the data that can be imported?

**Comment by geekgonecrazy** [comment]
Seems like it explains pretty well how the data is expected by the importer 👍

**Comment by marceloschmidt** [comment]
I tried to run a sample import and I get 
image

Here's my import.zip
[import.zip](https://github.com/RocketChat/Rocket.Chat.Docs/files/594476/import.zip)

And the structure of my zip file:

```
/tmp/import $ tree
.
├── channels.csv
├── my_test_import
│   └── msgs.csv
└── users.csv

1 directory, 3 files
```

And the content of my files:

```
 /tmp/import $ cat channels.csv
my_test_import,john.doe,private

 /tmp/import $ cat users.csv
john.doe,john@doe,John Doe

 /tmp/import $ cat my_test_import/msgs.csv
"marcelo","1479162481336","this is a test message"
"john.doe","1479162281336","Here we are"
```

Server output:

```
I20161116-09:53:09.594(-2)? CSV Importer ➔ debug CSV is now at importer_preparing_started.
I20161116-09:53:09.611(-2)? CSV Importer ➔ debug Ignoring the directory entry: import/
I20161116-09:53:09.616(-2)? CSV Importer ➔ debug Ignoring the directory entry: import/my_test_import/
I20161116-09:53:09.775(-2)? CSV Importer ➔ debug CSV is now at importer_preparing_messages.
I20161116-09:53:09.846(-2)? CSV Importer ➔ warn The loaded users count 0, the loaded channels 0, and the loaded messages 4
I20161116-09:53:09.849(-2)? CSV Importer ➔ debug CSV is now at importer_import_failed.
```

**Comment by marceloschmidt** [comment]
Are there plans to also specify which users are in which channels?

**Comment by graywolf336** [comment]
@marceloschmidt The reason yours failed is because your zip file isn't a flat zip and thus it wasn't a correctly setup csv zip file. I will add this to the documentation, but basically the zip file needs to be flat with no folder inside of it and just the files.

As for specifying the users in which channel, I had thought about that but I wasn't sure the best way to approach it. I'm open to suggestions.

**Review by geekgonecrazy — APPROVED** [review]

**Pull request merged**
