### PR TITLE
Docs: Explain the concept of webhooks

### PR DESCRIPTION
**Pull request by pixelbrackets**
Explain the existing integrations via WebHooks → Whats the general idea,
which types are available, what is the message format, what are limitations
(recommend to use the REST API for all enhanced features).

I had the same questions while trying for figure out the WebHook concept,
got some answers in the dev chat and thought that this clarification in the docs
may help others as well.

### CODE REVIEW

**Comment by graywolf336** [comment]
While mostly correct, it's not 100%. An outgoing integration can contain a script which does not have to post to a service to create a message in response to an event.

Also, there are several different triggers which can trigger an outgoing integration to be executed not just sending of messages.

Make sense?

**Comment by pixelbrackets** [comment]
Thanks for the feedback :) 

> An outgoing integration can contain a script which does not have to post to a service to create a message in response to an event.

Ah, I see. I'll fix this.

> Also, there are several different triggers which can trigger an outgoing integration to be executed not just sending of messages.

This seems to be a misunderstanding. I wrote that the result of the webhook may be a message  only. The webhook wont trigger any other events, like "create a new channel etc". But the webhook may be triggered by various events. I'll try to clarify this.

**Comment by pixelbrackets** [comment]
I pushed a new version with the fixes mentioned above.

**Comment by rafaelks** [comment]
@graywolf336 Can you review this one again, please?

**Comment by docsncode** [comment]
@graywolf336 are you happy with pixelbracket's changes and ready to merge?

**Comment by engelgabriel** [comment]
@pixelbrackets @SeanPackham @rafaelks I believe this is still not 100% correct. As @graywolf336 explained:

With *Scripts* you can point any WebHook to Rocket.Chat and process the request to print customized messages, define the username and avatar of the *user* of the message and change the channel where the message will be posted or you can cancel the request to prevent undesired messages.

And it is possible possible to trigger any other event with a WebHook (eg. “Create a new channel”).

**Review by engelgabriel — APPROVED** [review]

**Review by engelgabriel — APPROVED** [review]

**Comment by frdmn** [comment]
Rebased to resolve conflicts after new GitBook structure.

**Pull request merged**
