### PR TITLE
Add info  to binary based deployment for FreeBSD - PLEASE DO NOT MERGE YET - working with contributor lme 

### PR DESCRIPTION
**Pull request by Sing-Li**
might need to get linking syntax correct

### CODE REVIEW

**Comment by engelgabriel** [comment]
@Sing-Li is this still valid or going to be worked on?

**Comment by Sing-Li** [comment]
@engelgabriel   Yes.  We're actually waiting for the universal meteor project to release their binaries for Meteor 1.4.x  - which should be real soon.  4commerce-technologies-AG/meteor/issues/62

**Comment by rodrigok** [comment]
Should we merge this?

**Comment by geekgonecrazy** [comment]
The linked to document doesn't exist so that would need to be created before this could be merged. :(

**Comment by Sing-Li** [comment]
Yes. Highly outdated.  And contributor no longer active 😞    Closing the PR.

**Pull request closed without merging**
