### PR TITLE
[NEW] Bots and DDP Requests documentation

### PR DESCRIPTION
**Pull request by mikaelmello**
Documentation about changes (pending review) in https://github.com/RocketChat/Rocket.Chat/pull/10832

### CODE REVIEW

**Comment by MartinSchoeler** [comment]
@mikaelmello can you fix the linting? Just add some spaces before your lists and remove the indentation on the lists. Thanks!

**Comment by timkinnane** [comment]
Hey these docs are great, but I can't properly review until the feature being documented is merged into core.

@mikaelmello, do you have any communications from core team on that? Please ping me back on this issue when it's ready.

**Comment by MartinSchoeler** [comment]
@mikaelmello Could you please update this to reflect https://github.com/RocketChat/Rocket.Chat/pull/13609 Thanks!

**Comment by mikaelmello** [comment]
@MartinSchoeler, sure! I'll do it this weekend

**Pull request closed without merging**
