### PR TITLE
Updated React Native experimental user guide

### PR DESCRIPTION
**Pull request by ghost**
Completed the guide for React Native experimental application.

@diegolmello Let me know if any other features missing so that I can write about those too. :)

### CODE REVIEW

**Comment by ghost** [comment]
@diegolmello  Can you please review ?

**Review by MartinSchoeler — COMMENTED** [review]
About the images, maybe you can crop out the top bar (the one that shows the time and battery) and you might want to blur out some sensitive data on the images (like email addresses)

**Comment by saketkumar** [comment]
@MartinSchoeler Yes Sure. I thought same. I will update it.

**Comment by ghost** [comment]
@MartinSchoeler Yes Sure. I thought same. I will update it.

**Comment by Faria1212** [comment]
Outdated!

**Pull request closed without merging**
