### PR TITLE
add German User Group channel

### PR DESCRIPTION
**Pull request by localguru**
Note on the channel of the German Rocket.Chat User Group, founded with @TwizzyDizzy

### CODE REVIEW

**Comment by TwizzyDizzy** [comment]
Made it a little more clear what those channels are for.

I think it's a good idea to check back with RC folks like @tostanoski or @frdmn. Maybe we can also have a look for already existing groups that we could rename to the `ug_[language]` format.

Any feedback, guys?

Cheers
Thomas

**Comment by localguru** [comment]
@tostanoski: Tom, could you please review the PR. If you have any questions, feel free to contact Thomas or me.

**Comment by MartinSchoeler** [comment]
@localguru this PR still needs @Schoppa CLA signature. Thanks!

**Comment by TwizzyDizzy** [comment]
Has been superseeded by #974

**Pull request closed without merging**
