### PR TITLE
Provide SAML-specific terms

### PR DESCRIPTION
**Pull request by rhoerbe**
The current terms require some guessing, e.g. 'entrypoint' does not make clear whcih binding is implied.

### CODE REVIEW

**Comment by rhoerbe** [comment]
I would recommend to provide the SAML terms in the /admin/SAML form as well.

**Comment by docsncode** [comment]
@sampaiodiego could you recommend someone to review this PR?

**Comment by sampaiodiego** [comment]
maybe @rodrigok can help here..

**Review by engelgabriel — APPROVED** [review]

**Comment by engelgabriel** [comment]
@rhoerbe I have created https://github.com/RocketChat/Rocket.Chat/issues/8258

**Comment by rhoerbe** [comment]
The wording got mixed up a bit; you need to swap "location (URL) of the SingleLogoutService" (L13) and "location (URL) of the SingleSignonService" (L17). Otherwise LGTM.

**Pull request merged**
