### PR TITLE
Change "Adminstrate" to Administer

### PR DESCRIPTION
**Pull request by marginquack**
"Adminstrate" is both misspelled and not a word

### CODE REVIEW

**Comment by cbrummitt** [comment]
I independently made this change in my open PR https://github.com/RocketChat/Rocket.Chat.Docs/pull/61 in commit 1793a21bd3c5cd2481e20399a4ba2e9e13021eb1 so if we merge #61 then we can close this. (Apple's dictionary says that "administrate" is a "less common term for administer".)

**Comment by engelgabriel** [comment]
@cbrummitt please resolve the conflict?

**Comment by cbrummitt** [comment]
PR #61 was merged, and it changed "Administrate" to "Administer", so we can close this pull request; its change has already been made in PR #61.

**Comment by cbrummitt** [comment]
PR #61 was merged, and it changed "Administrate" to "Administer", so we can close this pull request; its change has already been made in PR #61.

**Pull request closed without merging**
