### PR TITLE
Updating README with correct installation steps

### PR DESCRIPTION
**Pull request by abhishekpc**
The README doesn't mention that a workspace has to be registered in order to install any app from the marketplace.

### CODE REVIEW

**Comment by MartinSchoeler** [comment]
Hey @abhishekpc Nice writing! Could you please sign the CLA? Thanks!

**Comment by abhishekpc** [comment]
@MartinSchoeler I signed the CLA.

We have started using Rocket Chat instead of Slack in the team recently. Quite impressive open source software.

We have found a few bugs and already reported to your team by my colleagues.

Look forward to contributing to the project within our skill set :)

**Review by MartinSchoeler — APPROVED** [review]
Looks Good To Me!

**Comment by MartinSchoeler** [comment]
@abhishekpc Glad to hear that! Welcome aboard!

**Pull request merged**
