### PR TITLE
Enchanced Webhooks Documentation

### PR DESCRIPTION
**Pull request by graywolf336**
Depends on https://github.com/RocketChat/Rocket.Chat.Docs.Generator/pull/14 and https://github.com/RocketChat/Rocket.Chat/pull/5823 to be both merged.

### CODE REVIEW

**Comment by frdmn** [comment]
The following integration were added to master in the mean time and needs to be moved as well as included in the `redirects.json` as well:

- Google-Calendar
- Jenkins
- ReplyGif
- RunDeck

**Comment by graywolf336** [comment]
There's an upcoming change to integrations that will mark this pull request invalid and I'll make sure the documentation is up to par when it gets merged.

**Comment by geekgonecrazy** [comment]
Closing per conversation with @graywolf336

**Comment by rodrigok** [comment]
Can we delete this branch?

**Pull request closed without merging**
