### PR TITLE
Added an revised script for newer Alerts

### PR DESCRIPTION
**Pull request by svrnwnsch**
I created a new alert on Azure with the new Action groups and they changed the webhooks to look more like described here: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-log-alerts-webhook 
I revised the script to work for me maybe this will help others too.

### CODE REVIEW

**Comment by frdmn** [comment]
Rebased to reflect new structure of GitBooks.

**Comment by frdmn** [comment]
@svrnwnsch Is this PR still up-to-date?

**Comment by svrnwnsch** [comment]
I am still using this script and it still works for me.

**Review by Fishbowler — APPROVED** [review]

**Comment by Fishbowler** [comment]
Thanks for the contribution! Merged! 👍

**Pull request merged**
