### PR TITLE
[NEW] Adds documentation for newer Poll App features

### PR DESCRIPTION
**Pull request by RonLek**
- Adds detailed documentation for the newer features of the Poll App:
  -  Word Cloud Generation.
  - Mixed Visibility Polls.
  - Adding user-defined options.
  - Template Based Polls.
  - Live Polls.
- Adds documentation for Poll App configuration settings.

### CODE REVIEW

**Comment by RonLek** [comment]
@murtaza98 @sampaiodiego please take a look. We can merge this in as soon as all the remaining [3 PRs](https://github.com/RocketChat/rocket.chat.app-poll/pulls) are merged. Please let me know in case something needs to be modified within this one meanwhile. Thanks.

**Review by murtaza98 — APPROVED** [review]
LGTM!!

**Comment by murtaza98** [comment]
@Faria-TechWrite I've reviewed the documentation for this PR. Can we please merge it?

**Comment by Faria1212** [comment]
Thank you @murtaza98

**Pull request merged**
