### PR TITLE
[Fix] remove extra *

### PR DESCRIPTION
**Pull request by Deepak-learner**

### CODE REVIEW

**Comment by Faria1212** [comment]
Merged manually

**Comment by Deepak-learner** [comment]
@Faria-TechWrite what do you mean by merged manually?

**Comment by Faria1212** [comment]
Well, there are sync issues between gitbook and github(which gitbook guys
are working on). Branches are out of sync. So I cant merge them from
github. I go in on gitbook and do it myself. And most of the requests you
are sending are about the outdated information you are seeing on github
(which is already correct on gitbook). Please check the article first on
https://docs.rocket.chat/ to see if it actually needs improvement before
suggesting the improvement on github. Thank you.

**Comment by Deepak-learner** [comment]
Okay. I got it. Thanks for the information.

**Pull request closed without merging**
