### PR TITLE
Added steps in quick-start readme

### LINKED ISSUE #1548: set Python Interpreter to version > 2.5.0 and < 3.0.0
In the quick start guide doc under developer-guides, there is no step for setting the appropriate python interpreter version. 
As a large number of contributors have their default python interpreter version set to 3.7, running
`meteor npm install` will throw unexpected errors associated with node-gyp.
I would like to add an additional step demonstrating the same.

### PR DESCRIPTION
**Pull request by aviral243**
- Added a 4th step in quick-start readme demonstrating how to set up the appropriate python interpreter for new users.

-  FIXES #1548

### CODE REVIEW

**Comment by grahamsmith** [comment]
@aviral243 can you rebase this please and we can get it reviewed asap. Thanks 👍

**Comment by aviral243** [comment]
@grahamsmith Done. :)

**Comment by grahamsmith** [comment]
@aviral243 thanks for rebasing. Most of the files have moved so your rebase is not quite complete. Can you check where thew quickstart is now and update and push. Thanks

**Comment by MartinSchoeler** [comment]
The getting started doc changed a lot since this PR and I don't believe this can be merged as it is now, it would be necessary to re write it with the current doc as base. Feel free to contact me / start a new PR if you think we can improve the current docs. Thanks!

**Pull request closed without merging**
