### PR TITLE
Fix API call: get by query parameters

### PR DESCRIPTION
**Pull request by adpe**
Instead of get the response by json array

### CODE REVIEW

**Comment by MarcosSpessatto** [comment]
@adpe sorry but I could not see the difference by removing the json header. :thinking:

**Review by MarcosSpessatto — COMMENTED** [review]
@adpe sorry but I could not see the difference by removing the json header. thinking

**Comment by adpe** [comment]
> @adpe sorry but I could not see the difference by removing the json header. thinking

Mhm - you don't pass in this call the data by json as you set the parameter by the URL. So, this header is not necessary? In my environment it was not working setting this header.

**Comment by MarcosSpessatto** [comment]
Weird, it should works with the header as well. Can you please add your change to the `channels.counters` and `im.counters` also?

**Comment by adpe** [comment]
Hi @MarcosSpessatto 

Just tested it out again, it's working now. I think I've done some mistake using this last time.

**Pull request closed without merging**
