### PR TITLE
[NEW] Companion docs update to RC#11236 (pruning and retention policies)

### PR DESCRIPTION
**Pull request by vynmera**
This PR is the companion to https://github.com/RocketChat/Rocket.Chat/pull/11236, a PR that introduces a GUI for `rooms.cleanHistory`, and adds retention policies.

### To do
- [X] Update all changed APIs
  - [X] `rooms.cleanHistory` (add 4 optional fields)
- [X] Update permissions list
- [x] Write a page on pruning channels
- [x] Write a page on how to set up retention policies
  - [X] Global policies
  - [X] Per-channel policies and how they interact with global policies
  - [x] Add its label to the channel info page

### CODE REVIEW

**Comment by vynmera** [comment]
I'm taking this out of [WIP] because the main PR is nearing completion. I am still accepting new features there, so the same will go for this PR - if there are any guides you feel should be added, feel free to speak up :)

**Comment by MartinSchoeler** [comment]
@vynmera These docs are looking good, I will still not do the final approve as you said new topics can be added depending on the main PR.

**Comment by vynmera** [comment]
@MartinSchoeler The PR was merged, I updated the docs a bit during the time, please look through them and tell me what you think :)

**Comment by vynmera** [comment]
BTW, there's links to articles in this PR in the web UI, so it's quite important the merge happens on time, otherwise people will be stuck on our 404 :)

**Review by MartinSchoeler — APPROVED** [review]

**Comment by MartinSchoeler** [comment]
@vynmera Thanks for writing documentation for that awesome feature!

**Pull request merged**
