### PR TITLE
initial content for user docs on notifications

### PR DESCRIPTION
**Pull request by rasos**
Describing basic mechanism of notifications, after having studied the code, see https://github.com/RocketChat/Rocket.Chat/issues/6988

Still can't see that topic in the official docs: https://rocket.chat/docs/user-guides/

Debian update

### CODE REVIEW

**Comment by rasos** [comment]
closes #485 when accepted

**Comment by MartinSchoeler** [comment]
@rasos Thank you for contributing to the Rocket.Chat Documentation, can you resolve the conflicts? Also, can you give us more info on your changes on the Debian page? Thanks!

**Comment by rasos** [comment]
@MartinSchoeler the Debian update is about stretch, as nobody will install it on wheezy or jessy anymore.  You see the difference here: https://github.com/RocketChat/docs/pull/486/commits/25d59487fd64b8fbbeab0ad43b2762c8b05e371e

The docs on content notification are new, they were empty.

It seems I do not have sufficient rights to approve my own merge request.

**Comment by MartinSchoeler** [comment]
@rasos there is no need for you to approve the pr, it looks good to me, but you need to sync this branch with the `master` branch and resolve the conflicts before we can approve the pr. Thanks!

**Comment by rasos** [comment]
@MartinSchoeler unfortunately I did not check out locally but edited in the github web, which tells me "The conflict is too complex to be solved in the web interface". This means I would need to restart the process again - not sure when I will have time for that.

**Pull request merged**
