### PR TITLE
FIXES[#1194] Fixed the `Can you help?` link

### PR DESCRIPTION
**Pull request by sudipt1999**
Now it will be redirecting it to Readme.md file of `/developer-guides/ui-and-theming/components/README.md`

### CODE REVIEW

**Comment by Rodriq** [comment]
@sudipt1999  I think this url is not suppose to point back to the `/developer-guides/ui-and-theming/components/README.md` page but rather to the `issues` page since it is an incomplete feature that needs development(help)
@MartinSchoeler if confirmed, i'll send a patch.

**Comment by sudipt1999** [comment]
@Rodriq  I already have a pr for this !Will close once that merges

**Comment by Rodriq** [comment]
> @Rodriq I already have a pr for this !Will close once that merges

Okay @sudipt1999 yea you are right I'll close when your PR is merged.
  Like I tried saying earlier, I think it should be pointing to the `issues` page since it's an incomplete feature and they need work/help(ers) there.

**Comment by MartinSchoeler** [comment]
The button at the end of the page already links to the GitHub page of this article. We will probably remove this article as well. Closing this for now.

**Pull request closed without merging**
