### PR TITLE
Change node.js version from 4.8.4 to 8.8.1 

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Merge after 0.60.0 is released: 

Ref: RocketChat/Rocket.Chat#8715

### CODE REVIEW

**Comment by sampaiodiego** [comment]
if we include https://github.com/RocketChat/Rocket.Chat/pull/9085 to `0.60.0` NodeJS version will be `8.9.3`

**Review by JSzaszvari — CHANGES_REQUESTED** [review]
Looks like you'll need to update it to 8.9.3 based on https://github.com/RocketChat/Rocket.Chat/pull/9085#issuecomment-351029191

**Comment by JSzaszvari** [comment]
Beat me to to by seconds @sampaiodiego haha

**Comment by sampaiodiego** [comment]
hahaha.. thanks @jszaszvari =D

**Comment by geekgonecrazy** [comment]
@sampaiodiego @jszaszvari there we go :)

Updated through webui... that was more painful then it should have been. :joy:

**Pull request merged**
