### PR TITLE
Unify mongo connection

### LINKED ISSUE #322: Unify suggested mongo connection strings
Ref: https://github.com/RocketChat/Rocket.Chat/issues/7439

### PR DESCRIPTION
**Pull request by vcapretz**
the database name was inconsistent and the docker-compose image names as well
now every mongo connection string should be similar

it closes #322

### CODE REVIEW

**Review by geekgonecrazy — CHANGES_REQUESTED** [review]
I agree on the database name consistency, so thanks for that.  The db name you changed db to mongo but didn't update the links.  I think i'd personally prefer the container name to be `db` as that's what most of us use when we give examples to people just off hand.  So better that the docs stay in tune with that.

**Comment by vcapretz** [comment]
hey @geekgonecrazy thank's for reviewing it! 

So the container name should be `db` and the database I can keep being `rocketchat`?

**Comment by engelgabriel** [comment]
Thanks @vcapretz

I also agree that the container name should be `db` and the database should be `rocketchat`

**Comment by vcapretz** [comment]
done @engelgabriel

**Review by geekgonecrazy — APPROVED** [review]

**Comment by geekgonecrazy** [comment]
@vcapretz thanks!

**Pull request merged**
