### PR TITLE
User guide changes add Jira outbound integration

### PR DESCRIPTION
**Pull request by Rohlik**
I think that right category is "Integration" not "Import".

### CODE REVIEW

**Comment by Rohlik** [comment]
Also adding info about Jira integration.
PS: Sorry for spam.

**Comment by Rohlik** [comment]
Still no review??

**Comment by geekgonecrazy** [comment]
@marceloschmidt as most familiar with slackbridge, can you take a look?

**Comment by geekgonecrazy** [comment]
Actually disregard.  The bulk of this is Jira which looks fine.  

The slackbridge re-categorization idk if I agree with.  It's currently not in Rocket.Chat treated as an integration.  Its more of an import / export as it's importing messages into rocket.chat

**Review by geekgonecrazy — CHANGES_REQUESTED** [review]
Other then the re-categorizing of slack bridge all the other changes look good :+1:  Please revert that for now. 

The slackbridge is intended as a shim to allow groups to export slack import into Rocket.Chat and then run the bridge to keep the import going until they are able to get all of their users moved over to Rocket.Chat.

While in a way its an integration.  It purpose really is to import.

If anything at all... I'd say we need a bridge section when we get other bridges in place.

Lets keep this PR for updating jira as that's what the bulk of the changes are doing :+1:

**Comment by Rohlik** [comment]
@geekgonecrazy  Okey, I revert category change for Slack-bridge.

**Review by geekgonecrazy — APPROVED** [review]

**Pull request merged**
