### PR TITLE
Add link to attachments object description

### PR DESCRIPTION
**Pull request by ear-dev**
Currently the description of the message object in the developer guide does not describe the contents of the attachments object.  This PR adds a link to where a complete description can be found.

### CODE REVIEW

**Comment by MartinSchoeler** [comment]
@ericrosenthal Could you sign the CLA please? Thanks!

**Comment by ear-dev** [comment]
@MartinSchoeler I have signed as ear-dev, I'm not exactly sure why it's also showing ericrosenthal (my full name)

**Comment by MartinSchoeler** [comment]
@ear-dev perhaps you have more than one account logged, since there are 2 users committing in this PR. https://github.com/ericrosenthal and https://github.com/ear-dev

**Review by MartinSchoeler — APPROVED** [review]

**Comment by MartinSchoeler** [comment]
Alright, Looks good to me, thanks for the contribution!

**Pull request merged**
