### PR TITLE
Youtube Broadcasting docs

### PR DESCRIPTION
**Pull request by MartinSchoeler**
Docs for: https://github.com/RocketChat/Rocket.Chat/pull/10127

### CODE REVIEW

**Review by gdelavald — COMMENTED** [review]
Please add docs to when Livestream is enabled but Broadcast is not.

**Comment by MartinSchoeler** [comment]
@gdelavald done

**Review by gdelavald — APPROVED** [review]

**Comment by saschafoerster** [comment]
I am missing information about, where to get the different API and links in the options: 
I found API Key, Client ID & Secret, but I don't know, where to find the Broadcasting_media_server_url? I searched here, but I didn't find out what to do? https://support.google.com/youtube/answer/2907883?hl=de

**Comment by faziloub** [comment]
yes there is no broadcasting_media url

**Comment by Syirrus** [comment]
> yes there is no broadcasting_media url

Yes ditto!

**Pull request merged**
