### PR TITLE
Add note to Uncomment console.log to debug in Telegram Integration

### PR DESCRIPTION
**Pull request by robbyoconnor**

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@robbyoconnor I might be missing something.  But why do we need the console.log uncommented?  I would think this would only be needed in a development environment

**Comment by robbyoconnor** [comment]
@geekgonecrazy either it needs to be commented, or the comment above it needs to change :)

**Comment by robbyoconnor** [comment]
@geekgonecrazy fixed it. Prior it looked like an oversight -- I copied/pasted straight from The integration I was using. Now it's clearer. The console.log is quite useful.

**Review by geekgonecrazy — APPROVED** [review]
Thanks :+1: I think that's totally acceptable.  Just didn't want loose console.log's as a default :grin:

**Comment by robbyoconnor** [comment]
Well it's there -- they just have to read it..

**Pull request merged**
