### PR TITLE
Windows Installation Guide v2.0.1

### PR DESCRIPTION
**Pull request by matholum**
Tweaks and missing steps found during support

### CODE REVIEW

**Comment by frdmn** [comment]
May I ask why you removed the contribution and promotion guide, README as well as the "Reporting security guidelines" files?

**Comment by matholum** [comment]
@frdmn - Sorry, my bad.I didn't intend to... I thought you guys did that. Let me add them back

**Comment by matholum** [comment]
Turns out Windows stripped them because of the '?'...

**Comment by engelgabriel** [comment]
Maybe we should remove the question mark form the name? It was my idea initially, but now I can see that it will cause problems.

**Comment by matholum** [comment]
@engelgabriel - I already moved it from the folder name and adjested the paths in README.md. I think it will be ok now.

**Pull request merged**
