### PR TITLE
Refactor the email admin guide

### PR DESCRIPTION
**Pull request by antgel**
Make it flow better for (non-)docker users, remove some spurious content.

### CODE REVIEW

**Comment by frdmn** [comment]
LGTM! I really like the proper Markdown formatting (headlines, etc.)

What does the rest of @RocketChat/documentation-and-wiki think?

**Comment by geekgonecrazy** [comment]
LGTM as well 👍

**Comment by frdmn** [comment]
Thanks for the PR @antgel!

**Comment by antgel** [comment]
@alexweissman I believe that many people in the position of configuring an RC server will know this. If there are errors they will turn up in the logs. A large part of simplifying the docs was removing things that seemed to me to be too off-topic. I don't remember if I needed to reboot, it was a while ago (email filters)...

**Pull request merged**
