### PR TITLE
[REST API] Add description for users.generatePersonalAccessToken endpoints

### PR DESCRIPTION
**Pull request by shiqimei**
cc @MartinSchoeler @MarcosSpessatto. Would you please review the changes? Thanks :)

### CODE REVIEW

**Review by MarcosSpessatto — CHANGES_REQUESTED** [review]
@lolimay Can you please add this info to the others endpoints related to the personal access tokens? They also needs that permission. :slightly_smiling_face:

**Comment by shiqimei** [comment]
> @lolimay Can you please add this info to the others endpoints related to the personal access tokens? They also needs that permission.

OK, I will try to find them out 😉

**Comment by MarcosSpessatto** [comment]
> > @lolimay Can you please add this info to the others endpoints related to the personal access tokens? They also needs that permission.
> 
> OK, I will try to find them out
[Regenerate](https://github.com/RocketChat/docs/tree/master/developer-guides/rest-api/users/regeneratepersonalaccesstoken), [Remove](https://github.com/RocketChat/docs/tree/master/developer-guides/rest-api/users/removepersonalaccesstoken), [Get](https://github.com/RocketChat/docs/tree/master/developer-guides/rest-api/users/getpersonalaccesstokens)

**Comment by shiqimei** [comment]
@MarcosSpessatto, sorry for the delay! I've added this info into all endpoints related to the personal access tokens. Please review :)

**Pull request merged**
